//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public Cell()
        {
            this.Requirements = new HashSet<Requirement>();
            this.Teams = new HashSet<Team>();
        }
    
        public int CellID { get; set; }
        public string CellName { get; set; }
        public string Tag { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
