//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementRevision
    {
        public long RevisionID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Modified { get; set; }
        public string Message { get; set; }
        public byte Status { get; set; }
        public int RequirementID { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual RequirementText RequirementText { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
