//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementRating
    {
        public long RevisionID { get; set; }
        public decimal RatingA { get; set; }
        public decimal RatingB { get; set; }
        public decimal RatingC { get; set; }
        public Nullable<decimal> FinalRating { get; set; }
        public bool Approved { get; set; }
    
        public virtual RequirementRevision RequirementRevision { get; set; }
    }
}
