//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public long RevisionID { get; set; }
        public int UserID { get; set; }
        public byte RatingA { get; set; }
        public byte RatingB { get; set; }
        public byte RatingC { get; set; }
        public Nullable<decimal> FinalRating { get; set; }
        public string Comments { get; set; }
    
        public virtual RequirementRevision RequirementRevision { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
