//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.Teams = new HashSet<Team>();
            this.RequirementRevisions = new HashSet<RequirementRevision>();
            this.Elicitations = new HashSet<Elicitation>();
        }
    
        public int UserID { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<RequirementRevision> RequirementRevisions { get; set; }
        public virtual ICollection<Elicitation> Elicitations { get; set; }
    }
}
