//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.DateTime EventTime { get; set; }
        public byte ActionType { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> RequirementId { get; set; }
        public Nullable<int> Revision { get; set; }
    }
}
