//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Baselines = new HashSet<Baseline>();
            this.Memberships = new HashSet<Membership>();
            this.Modules = new HashSet<Module>();
            this.Requirements = new HashSet<Requirement>();
            this.StrongTypes = new HashSet<StrongType>();
            this.Templates = new HashSet<Template>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Baseline> Baselines { get; set; }
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<StrongType> StrongTypes { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
    }
}
