//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.RequirementRelations = new HashSet<RequirementRelation>();
            this.RequirementRelations1 = new HashSet<RequirementRelation>();
            this.RequirementRevisions = new HashSet<RequirementRevision>();
        }
    
        public int RequirementId { get; set; }
        public int Revision { get; set; }
        public int ProjectId { get; set; }
        public string RequirementName { get; set; }
        public int UserId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<RequirementRelation> RequirementRelations { get; set; }
        public virtual ICollection<RequirementRelation> RequirementRelations1 { get; set; }
        public virtual ICollection<RequirementRevision> RequirementRevisions { get; set; }
        public virtual User User { get; set; }
    }
}
