//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementText
    {
        public int RequirementId { get; set; }
        public int Revision { get; set; }
        public int TemplateId { get; set; }
        public byte FieldIndex { get; set; }
        public string FieldValue { get; set; }
    
        public virtual RequirementRevision RequirementRevision { get; set; }
        public virtual TemplateField TemplateField { get; set; }
        public virtual Template Template { get; set; }
    }
}
