//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementRelation
    {
        public int SourceReqId { get; set; }
        public int DestReqId { get; set; }
        public System.DateTime Modified { get; set; }
        public int UserId { get; set; }
        public Nullable<byte> RelationType { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual Requirement Requirement1 { get; set; }
        public virtual User User { get; set; }
    }
}
