//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementRevision
    {
        public RequirementRevision()
        {
            this.DiagramAttributes = new HashSet<DiagramAttribute>();
            this.RequirementTexts = new HashSet<RequirementText>();
            this.Baselines = new HashSet<Baseline>();
        }
    
        public int RequirementId { get; set; }
        public int Revision { get; set; }
        public int UserId { get; set; }
        public System.DateTime Modified { get; set; }
        public string Comment { get; set; }
        public string RequirementName { get; set; }
        public Nullable<byte> RequirementType { get; set; }
        public Nullable<int> TemplateId { get; set; }
    
        public virtual ICollection<DiagramAttribute> DiagramAttributes { get; set; }
        public virtual Requirement Requirement { get; set; }
        public virtual Template Template { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RequirementText> RequirementTexts { get; set; }
        public virtual UseCas UseCas { get; set; }
        public virtual ICollection<Baseline> Baselines { get; set; }
    }
}
