//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateField
    {
        public TemplateField()
        {
            this.RequirementTexts = new HashSet<RequirementText>();
        }
    
        public int TemplateId { get; set; }
        public byte FieldIndex { get; set; }
        public string FieldName { get; set; }
        public byte FieldType { get; set; }
        public string Format { get; set; }
        public string Hint { get; set; }
        public string URI { get; set; }
    
        public virtual ICollection<RequirementText> RequirementTexts { get; set; }
        public virtual Template Template { get; set; }
    }
}
