//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TigraEntities : DbContext
    {
        public TigraEntities()
            : base("name=TigraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Baseline> Baselines { get; set; }
        public DbSet<DiagramAttribute> DiagramAttributes { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<RequirementRelation> RequirementRelations { get; set; }
        public DbSet<RequirementRevision> RequirementRevisions { get; set; }
        public DbSet<Requirement> Requirements { get; set; }
        public DbSet<RequirementText> RequirementTexts { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<StrongType> StrongTypes { get; set; }
        public DbSet<TemplateField> TemplateFields { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<UseCaseFlow> UseCaseFlows { get; set; }
        public DbSet<UseCas> UseCases { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ActionType> ActionTypes { get; set; }
        public DbSet<FieldType> FieldTypes { get; set; }
        public DbSet<RelationType> RelationTypes { get; set; }
        public DbSet<RequirementType> RequirementTypes { get; set; }
    }
}
