//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseCas
    {
        public UseCas()
        {
            this.UseCaseFlows = new HashSet<UseCaseFlow>();
        }
    
        public int RequirementId { get; set; }
        public int Revision { get; set; }
        public string Summary { get; set; }
        public string Actors { get; set; }
        public string PreConditions { get; set; }
        public string PostConditions { get; set; }
    
        public virtual RequirementRevision RequirementRevision { get; set; }
        public virtual ICollection<UseCaseFlow> UseCaseFlows { get; set; }
    }
}
