//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseCaseFlow
    {
        public UseCaseFlow()
        {
            this.UseCaseFlows1 = new HashSet<UseCaseFlow>();
        }
    
        public long FlowId { get; set; }
        public int RequirementId { get; set; }
        public int Revision { get; set; }
        public byte FlowGroup { get; set; }
        public byte FlowNumber { get; set; }
        public byte StepNumber { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual ICollection<UseCaseFlow> UseCaseFlows1 { get; set; }
        public virtual UseCaseFlow UseCaseFlow1 { get; set; }
        public virtual UseCas UseCas { get; set; }
    }
}
