//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tigra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Memberships = new HashSet<Membership>();
            this.Ratings = new HashSet<Rating>();
            this.RequirementRelations = new HashSet<RequirementRelation>();
            this.RequirementRevisions = new HashSet<RequirementRevision>();
            this.Requirements = new HashSet<Requirement>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RequirementRelation> RequirementRelations { get; set; }
        public virtual ICollection<RequirementRevision> RequirementRevisions { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
    }
}
