CREATE DATABASE [Tigra] COLLATE Latin1_General_100_CI_AS;
GO

CREATE SCHEMA [Tigra];
GO

CREATE LOGIN [TigraApp] WITH PASSWORD = '#TigR4$h*cKD3ut5cH!@', DEFAULT_DATABASE = [Tigra];
GO

CREATE USER [TigraUser] FOR LogIN [TigraApp];
GO
